org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
flutter.versionCode=71370132
flutter.versionName=7.13.31
flutter.compileSdkVersion=36
flutter.targetSdkVersion=35
flutter.minSdkVersion=24
android.enableR8.fullMode=false
keyProperties=../key.properties
kotlin.code.style=official
