org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.workers.max=4
org.gradle.parallel=true
kotlin.daemon.jvmargs=-Xmx2G
android.useAndroidX=true
android.enableJetifier=true
flutter.versionCode=4
flutter.versionName=1.0.1
flutter.compileSdkVersion=36
flutter.targetSdkVersion=35
flutter.minSdkVersion=23
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home
